services:
  rag-backend:
    container_name: rag-app
    build: .
    
    # "host" mode allows the container to share the localhost network.
    # Note: This works great on Linux. On Mac/Windows, you might need to switch 
    # to 'ports: - "8000:8000"' if you can't access localhost:8000.
    network_mode: "host" 
    
    env_file:
      - .env
    
    # VITAL: This maps your current folder (.) to the container folder (/app)
    # This enables the live code updates.
    volumes:
      - .:/app
      
    # Ensures the server restarts when it sees file changes in the volume
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload